### PR TITLE
Fix: Make keybinds text/arrows visible

### PR DESCRIPTION
**Pull request by DokterKaj**

### CODE REVIEW

**Comment by uncenter** [comment]
Mind fixing https://github.com/catppuccin/discord/blob/53683e3fcdb558995a2255ddb9f9eb46fac9fc81/src/components/_chat.scss#L266-L269 while you are at it?

**Comment by DokterKaj** [comment]
Where does that show up?

**Comment by uncenter** [comment]
Go to a forum thread, type something into the search box.

**Comment by DokterKaj** [comment]
Alright, I see it

Looking through the inspector, it seems like without any override, `span[class^="key"]` defaults to `var(--interactive-active)` which is actually set to `$text` already
https://github.com/catppuccin/discord/blob/807261856fb5e481a44162917b6d07ad0b587435/src/components/_variables.scss#L294
Maybe we can remove the overrides for the text and just leave the ones for `svg g`?

**Comment by ToxicAven** [comment]
Is this ready to be merged?

**Comment by DokterKaj** [comment]
Yep

**Pull request merged**
