### PR TITLE
feat: use autogenerated class name mappings

### PR DESCRIPTION
**Pull request by ryanccn**
This PR fetches the source CSS from Discord and replaces `.mapped-*` class names in the theme CSS with the upstream classes instead of matching with `class` attributes, because attribute selectors are very slow compared to class ones.

## Pros

- Improves code readability
- Checks for nonexistent class names
- Up to 1.6x rendering speedup on a high-end laptop

Before: 278ms Rendering After: 172ms Rendering

## Cons

- May take a few minutes to update

### CODE REVIEW

**Comment by ryanccn** [comment]
We could of course run the GitHub Actions workflow even more frequently because it's free :p

**Comment by nullishamy** [comment]
It's not free, there are limits.

**Comment by ryanccn** [comment]
> It's not free, there are limits.

GitHub Actions usage of minutes and storage is free for public repositories though; the hard limits are more than enough for running a workflow even every five minutes.

However Discord probably doesn't update that often, and people don't reload *that* often, so perhaps a 1 hour cycle is tolerable

**Comment by nullishamy** [comment]
Oh, ok. I thought the limits were significantly lower haha. It's fine enough at 1h for now though, as you said.

**Comment by ToxicAven** [comment]
The regex fails to match to numbers. `.mapped-latin24CompactTimeStamp` fails to resolve as `latin`.

**Comment by ToxicAven** [comment]
It also only matches the first it finds, and not the most accurate option. `.mapped-activityUserPopoutV2` returned `.activity-1-H7ZUserPopoutV2`.

**Comment by rubyowo** [comment]
time to levenshtein distance?

**Comment by ToxicAven** [comment]
Also another huge problem: it only selects the first of its name. Discord repeats names constantly in its classes, but with different suffixes. `[class*="wrapper-"]` returns 537 matches in my case. many of those have different suffixes and will not be applicable to certain areas after closer selecting is done.

**Comment by ryanccn** [comment]
Should be completely fixed now (hopefull)

**Comment by ToxicAven** [comment]
Its not. As posted in the Discord:
>  my 🥺 emoji picker simply matches to `sprite`. the problem is there is `.sprite-1bxGvV` **and** `.sprite-2lxwfc` present in discords css. the emoji picker is on `2lxwfc` but the first sprite class to appear in the css is `1bxGvV`. Therefore the code matches to `.sprite-1bxGvV` which I can't even find a use of.
This is a critical issue, as it can't even get a 50% chance, once something gets narrowed down or uses a class with hundreds of definitions (`wrapper-` has 224 alone), it just isn't feasible.
The only Solution I see is to literally take every single definition found in the css and nest it:
```scss
.sprite-1bxGvV, .sprite-2lxwfc {
  // ...
}
```
This is simply not feasible, as once it compiles, or if you use a wide selector (eg. `wrapper`) It will be kilobytes for a single rule.

**Comment by ryanccn** [comment]
Should be all right now

**Comment by ryanccn** [comment]
Moving this to a personal project

**Pull request closed without merging**
