### PR TITLE
some fixes

### PR DESCRIPTION
**Pull request by tuhanayim**
1. Fixed thin scrollbars. Discord's default theme doesn't makes thin scrollbars track's colored, so I made it transparent. Making it different from transparent makes some visual bugs, for example we see scrollbar at server header popup.
image
image

2. Fixed server modals, boost page.
image
image

3. Fixed emoji popups. (From #11, thank you @andreasgrafen)
image
image

### CODE REVIEW

**Comment by tuhanayim** [comment]
Don't merge now. I found a few issues too.

**Comment by tuhanayim** [comment]
Updated main comment. I think PR is ready.

**Comment by andreasgrafen** [comment]
May I suggest making the Modal footer being accentuate in a darker tone similar to the original design choice?

**Comment by tuhanayim** [comment]
Ah yes. Modal footer should be darker. Thank you.
And again, im so sorry about your PR. Unlucky timing :c

**Comment by andreasgrafen** [comment]
No need to be sorry! It's all fine. c:
When other people work on it I can lay back again and go back to only nagging. :'D

**Comment by tuhanayim** [comment]
Looks OK to me. Thoughts?
image

**Comment by andreasgrafen** [comment]
Lovely! :3

**Comment by tuhanayim** [comment]
Discord why?? Why are you using specific color instead of variabled one color :/
image

**Comment by tuhanayim** [comment]
This theme looks new but I think it needs to be rewritten. The way we colorize classes looks unsafe to me, and instead using color variables we use colors directly. Which makes code and maintainability more complex.

Also Discord's default theme is very very complex. They sometimes use variables, sometimes not. We have to check almost every single element for bugless theme.

**Comment by andreasgrafen** [comment]
> This theme looks new but I think it needs to be rewritten. The way we colorize classes looks unsafe to me, and instead using color variables we use colors directly. Which makes code and maintainability more complex.

I agree! This is exactly what I thought when I opened the file earlier. I also think that using partial class matching is very likely to prevent this theme from breaking if there were to be an update that changes the generated class names.
This probably should be discussed in a seperate Issue tho.  #12 c:

**Pull request merged**
