### PR TITLE
Add Vencord instructions

### PR DESCRIPTION
**Pull request by Arguability**
Add instructions for usage on Vencord

### CODE REVIEW

**Comment by ToxicAven** [comment]
I don't really know if this is a good idea, frankly at some point i'd like to declutter the readme with less of these random instructions. I'll leave this unmerged for now as a reference point.

**Comment by TakenMC** [comment]
Maybe have drop down menus that will have the info but not have a mess

**Comment by TheKodeToad** [comment]
You can do the same thing as you do with BetterDiscord now anyway

**Comment by ToxicAven** [comment]
The readme will be rewritten in a few hours so I will close this for now.

**Pull request closed without merging**
