### PR TITLE
Fix Modals and Popups

### PR DESCRIPTION
**Pull request by andreasgrafen**
This aims to fix the miscoloured modals and the background visiblity for the smaller popups.
<br>

Modals:

<br>

Popups:

### CODE REVIEW

**Comment by tuhanayim** [comment]
I already fixed, #10. And looks like you formatted the entire file so we can't see the real diff.

**Comment by andreasgrafen** [comment]
uugh.. Must be some `.editorconfig` setting that wasn't applied and which got autoformatted when I saved the file? annoying..

The changes start on line 145. I think it's slightly different from what you have done? Your changes seem to be a little more extensive tho.

**Comment by tuhanayim** [comment]
I fixed scrollbar thing, server modals and boost page background. I still work on PR message.

**Comment by andreasgrafen** [comment]
If you'd put the emoji popup thingy into your changes as well I could close this PR to simplify things? c:

**Comment by tuhanayim** [comment]
I put it now. Thanks for your effort by the way.

**Comment by andreasgrafen** [comment]
> I put it now. Thanks for your effort by the way.

Figured I might as well help out when I find something instead of just nagging all the time. c:

**Pull request closed without merging**
